### ISSUE TITLE
Kotlin Language Support

### ISSUE THREAD

**Issue by bruxisma** [ixm-one/ixm#2]
CMake does not currently support Kotlin. Neither the JVM nor Native compiler is designed to work with it in the slightest. Additionally, there is no language support for Java either. It is instead treated as a tool generator. 

That said, Kotlin is, in my opinion one of the best ways to interact with Android. I'm about 30 years old and have never written a line of Java. I'd frankly like to keep it that way. Supporting Kotlin (or proving that 'native' support is unwieldy or requires a different approach) is sorely needed, especially before IXM hits its 1.0 release.

## TODO

- [ ] Toolchain Detection (Including Java)
- [ ] Kotlin/Native Interop (`cinterop` tool)
- [ ] Generating Jar and native tools

**Comment by slurps-mad-rips** [comment]
See comment on #3

**Comment by bruxisma** [comment]
Closing, as this project has burned me out, and I cannot continue working on it in its current state. CMake has changed massively since this project was started. Most of it is no longer necessary. A new repository will be launched in September.
