### ISSUE TITLE
Go Language Support

### ISSUE THREAD

**Issue by bruxisma** [ixm-one/ixm#3]
Google's Go language is extremely ubiquitous at this point. However, `cgo` support is absolute trash. It would be nice if, somehow, we could have CMake build a go project while also handling the correct cgo flag generation before compiling. This would make working with golang easier for everyone in the long run.

## TODO

- [ ] Toolchain Detection
- [ ] Compiling Go packages
- [ ] Linking Go packages
- [ ] cgo integration
- [ ] Cross Compiling Support for cgo

**Comment by slurps-mad-rips** [comment]
Builtin Language support (via CMake's "enable language") is no longer a priority. Adding sources via `target(SOURCES)` is the new approach. In case it isn't obvious: I absolutely despise how awful adding support for a custom language to CMake is. It's terrible :/

**Comment by bruxisma** [comment]
Closing, as this project has burned me out, and I cannot continue working on it in its current state. CMake has changed massively since this project was started. Most of it is no longer necessary. A new repository will be launched in September.
